version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "start:dev"]

volumes:
  postgres_data:
